export const data = [
    {
      id: 1,
      type: "Vouchers",
      name: "Voucher 50.000",
      img: "/assets/vouchers.png",
      point: 50000,
    },
    {
      id: 2,
      type: "Products",
      name: "Products 100.000",
      img: "/assets/product.png",
      point: 100000,
    },
    {
      id: 3,
      type: "Giftcard",
      name: "Giftcard 100.000",
      img: "/assets/giftcard.png",
      point: 100000,
    },
    {
      id: 4,
      type: "Vouchers",
      name: "Voucher 200.000",
      img: "/assets/vouchers.png",
      point: 200000,
    },
    {
      id: 5,
      type: "Products",
      name: "Products 50.000",
      img: "/assets/product.png",
      point: 50000,
    },
    {
      id: 6,
      type: "Giftcard",
      name: "Giftcard 50.000",
      img: "/assets/giftcard.png",
      point: 50000,
    },
    {
      id: 7,
      type: "Vouchers",
      name: "Voucher 150.000",
      img: "/assets/vouchers.png",
      point: 150000,
    },
    {
      id: 8,
      type: "Products",
      name: "Products 300.000",
      img: "/assets/product.png",
      point: 300000,
    },
    {
      id: 9,
      type: "Giftcard",
      name: "Giftcard 300.000",
      img: "/assets/giftcard.png",
      point: 300000,
    },
    {
      id: 10,
      type: "Vouchers",
      name: "Voucher 250.000",
      img: "/assets/vouchers.png",
      point: 250000,
    },
    {
      id: 11,
      type: "Products",
      name: "Products 500.000",
      img: "/assets/product.png",
      point: 500000,
    },
    {
      id: 12,
      type: "Giftcard",
      name: "Giftcard 150.000",
      img: "/assets/giftcard.png",
      point: 150000,
    },
  ];
  